import { StyleSheet } from 'react-native';

const PRIMARY_BLUE = '#2979FF';
const PRIMARY_BLUE_LIGHT = '#E3F2FD';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f7fb',
    },
    header: {
        padding: 24,
        paddingTop: 40,
        paddingBottom: 100,
    },
    headerLabel: {
        fontSize: 32,
        fontWeight: '300',
        color: '#fff',
        letterSpacing: 0.5,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: '700',
        color: '#fff',
        marginTop: -8,
    },
    headerSubtitle: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.9)',
        marginTop: 8,
    },
    searchCard: {
        backgroundColor: '#fff',
        marginHorizontal: 20,
        marginTop: -60,
        padding: 24,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 10 },
        elevation: 8,
    },
    inputGroup: {
        marginBottom: 20,
        zIndex: 30,
    },
    fromInputGroup: {
        marginBottom: 20,
        zIndex: 50,
    },
    label: {
        fontSize: 13,
        color: '#9CA3AF',
        marginBottom: 8,
        fontWeight: '400',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingHorizontal: 14,
    },
    inputIcon: {
        marginRight: 8,
    },
    input: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 15,
        color: '#333',
    },
    suggestionsBox: {
        position: 'absolute',
        top: 78,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 2 },
        elevation: 40,
        maxHeight: 200,
        zIndex: 1000,
    },
    suggestionsList: {
        maxHeight: 200,
    },
    suggestionItem: {
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    suggestionContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    suggestionLeft: {
        flex: 1,
    },
    suggestionStationName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    suggestionCity: {
        fontSize: 13,
        color: '#9CA3AF',
    },
    suggestionCode: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6B7280',
        marginLeft: 12,
    },
    searchButton: {
        backgroundColor: '#2979FF',
        borderRadius: 14,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 12,
        shadowColor: '#2979FF',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    searchButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    swapButtonContainer: {
        alignItems: 'center',
        marginVertical: -10,
        zIndex: 40,
    },
    swapButton: {
        backgroundColor: '#2979FF',
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2979FF',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    errorText: {
        color: '#FF3B30',
        fontSize: 14,
        marginTop: 12,
        textAlign: 'center',
    },
    resultsSection: {
        padding: 16,
    },
    resultsTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
        marginBottom: 12,
    },
    trainCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    trainHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    trainNumber: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
    },
    trainName: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    trainTypeBadge: {
        backgroundColor: PRIMARY_BLUE_LIGHT,
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 8,
    },
    trainTypeText: {
        fontSize: 12,
        color: PRIMARY_BLUE,
        fontWeight: '600',
    },
    routeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    timeBlock: {
        alignItems: 'center',
    },
    timeText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
    },
    stationCodeText: {
        fontSize: 12,
        color: '#999',
        marginTop: 4,
    },
    durationBlock: {
        alignItems: 'center',
    },
    durationText: {
        fontSize: 12,
        color: '#666',
        marginTop: 4,
    },
    trainFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        paddingTop: 12,
    },
    fareLabel: {
        fontSize: 12,
        color: '#999',
    },
    fareText: {
        fontSize: 20,
        fontWeight: '700',
        color: PRIMARY_BLUE,
        marginTop: 2,
    },
    bookButton: {
        backgroundColor: PRIMARY_BLUE,
        paddingHorizontal: 24,
        paddingVertical: 10,
        borderRadius: 10,
    },
    bookButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
});

export default styles;
